### PR TITLE
Sort people meeting

### LINKED ISSUE #58: Sort people by name

### LINKED ISSUE #62: Sort meetings (by dates and priority)
Should be sortm priority or sortm dates

### PR DESCRIPTION
**Pull request by totoyoyo**
Add sorts and unsorts for meetings and people

### CODE REVIEW

**Comment by totoyoyo** [comment]
Should look good to merge.

**Comment by totoyoyo** [comment]
Oh no the tests fail.

**Comment by totoyoyo** [comment]
I fixed the tests.

**Comment by hengyiqun** [comment]
LGTM

**Comment by skinnychenpi** [comment]
LGTM as well.

**Pull request merged**
