### PR TITLE
Add person connection storage

### LINKED ISSUE #81: Store Connections into the storage
so that the every time the user relaunches the program will restore the connections created.

### PR DESCRIPTION
**Pull request by Maurice2n97**
Person - Connection storage has been implemented.
All persons related to the meeting will be saved offline.

Note that there are a few minor suggestions with person meeting connection
Maybe we can create a read-only interface for person-meeting connection
this will ensure that only Model Manager can modify the person meeting connection internally
Also, we should ensure that all meetings have a non Null person meeting connection
This can be done whenever we add a meeting through the model, we set the person meeting connection to it.

Also seems like we need check a lot of conditions
For example if delete/edit person -> we need to remove/edit from connections 
if delete/edit meeting, we need to remove/edit from connections the meeting

### CODE REVIEW

**Comment by skinnychenpi** [comment]
You mentioned that: "Also seems like we need check a lot of conditions
For example if delete/edit person -> we need to remove/edit from connections
if delete/edit meeting, we need to remove/edit from connections the meeting"

I have already implemented those cases except the clear command. Will do it later.

**Comment by skinnychenpi** [comment]
Also it seems that the CI didn't pass.

**Comment by Maurice2n97** [comment]
Fixing CI

**Comment by skinnychenpi** [comment]
> Fixing CI

OK.

**Pull request merged**
